config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

  resources :preferences

  devise_for :users
  root 'landing#index', :as => :index_preferences

end

app/models/preference.rb
class Preference < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :preferences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  	if params[:pid]
	  	if params[:toggle]
	  		preference = current_user.preferences.find(params[:pid])
	  		if preference.enable == 1
	  			preference_order = Preference.all
	  			preference_order.each do |f|
	  				if f.order < preference.order and f.enable==1
	  					f.order+=1
	  					f.save!
	  				end
	  			end
	  			preference.enable = 0
	  			preference.order = -1
	  		else
	  			preference_order = Preference.all
	  			preference_order.each do |f|
	  				if f.enable==1 and f.order==0
	  					f.order+=1
	  					f.save!
	  				end
	  			end
	  			preference_order_first = Preference.order(:order)
	  			preference_order_first.each do |f|
	  				if f.order>0
	 					preference.enable = 1
	  					preference.order = f.order - 1
	  					break
	  				end
	  			end
	  		end
	  	preference.save!
	  	end

	  	if params[:op]
	  		preference = current_user.preferences.find(params[:pid])
	  		if params[:op].to_i==1
	  			select_preference = current_user.preferences.where(order: preference.order+1).first
	  			select_preference.order-=1 
	  			preference.order+=1
	  		else
	  			select_preference = current_user.preferences.where(order: preference.order-1).first
	  			select_preference.order+=1
	  			preference.order-=1
	  		end
	  		preference.save!
	  		select_preference.save!
	  	end
	  	redirect_to index_preferences_path
	  end

  	if current_user.preferences.exists?
    @preferences = current_user.preferences.order(order: :desc)
    else
    Preference.create!(:name=>"WhatsApp",:order=>1,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Text Messages",:order=>2,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Email",:order=>3,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Phone Calls",:order=>0,:enable=>1,:user_id=>current_user.id)
    @preferences = current_user.preferences.order(order: :desc)
  end
  end
	respond_to do |format|
		format.html
		format.js
	end

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    if current_user.preferences.exists?
    @preferences = current_user.preferences
    else
    Preference.create!(:name=>"WhatsApp",:order=>0,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Text Messages",:order=>0,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Email",:order=>0,:enable=>1,:user_id=>current_user.id)
    Preference.create!(:name=>"Phone Calls",:order=>0,:enable=>1,:user_id=>current_user.id)
    @preferences = current_user.preferences
  end
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, notice: 'Preference was successfully created.' }
        format.json { render :show, status: :created, location: @preference }
      else
        format.html { render :new }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @preference }
      else
        format.html { render :edit }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url, notice: 'Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:name, :order, :enable)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/landing/_preference.html.erb
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="timeline">
                            <% @preferences.each do |f|%>
                                <li>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header no-border" style="text-align:center;">
                                        		<% if f.enable == 1 %>
                                        			<div style="display:inline"><%= f.name %></div>
                                        				<% if f.order!=3 %>
                                        					<a href="./landing/index?op=1&pid=<%=f.id%>" class="up_arrow_box" data-remote="true" style="margin-left:30px">
                                        					</a>
                                        				<% end %>
	                                        	<% if f.order!=0 %>
	                                        		<a href="./landing/index?op=0&pid=<%=f.id%>" style="margin-left:10px" class="down_arrow_box" data-remote="true">
	                                        		</a>
	                                        	<% end %>
                                			<%= link_to ' Disable?', index_preferences_path(:toggle => 1, :pid => f.id),:remote => true,:class=>"enable" %>        
                                        	<% else %>
                                        	<div style="text-decoration:line-through;display:inline;color:#D0D0D0"><%= f.name %></div>
                                        	<%= link_to ' Enable?', index_preferences_path(:toggle => 1, :pid => f.id),:remote => true,:class=>"enable" %>
                                        	<% end %> <br>
                                        </h3>
                                    </div>
                                </li>
                                <% end %>
                            </ul>
                        </div><!-- /.col -->
                    </div><!-- /.row -->

app/views/landing/index.html.erb
<!DOCTYPE html>
<html style="min-height: 1843px;"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="UTF-8">
        <title>Preferences</title>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <link href="./AdminLTE   Timeline_files/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="./AdminLTE   Timeline_files/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="./AdminLTE   Timeline_files/ionicons.min.css" rel="stylesheet" type="text/css">
        <link href="./AdminLTE   Timeline_files/AdminLTE.css" rel="stylesheet" type="text/css">

    </head>
    <body class="skin-blue  pace-done" style="min-height: 1843px;"><div class="pace  pace-inactive"><div class="pace-progress" data-progress-text="100%" data-progress="99" style="width: 100%;">
  <div class="pace-progress-inner"></div>
</div>
<div class="pace-activity"></div></div>
        <div class="wrapper row-offcanvas row-offcanvas-left" style="min-height: 633px;">
                <section class="content-header">
                    <h1 style="text-align:center">
 						Hi user! Here are your communication preferences 
                     </h1>
                </section>
                <section class="content">
                	<div id ="preferences">
						<%= render('preference') %>
					</div>
                </section>
             </div>
        <script src="./AdminLTE   Timeline_files/jquery.min.js"></script>
        <script src="./AdminLTE   Timeline_files/bootstrap.min.js" type="text/javascript"></script>
        <!-- AdminLTE App -->
        <script src="./AdminLTE   Timeline_files/app.js" type="text/javascript"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="./AdminLTE   Timeline_files/demo.js" type="text/javascript"></script>
    
</body></html>

app/views/landing/index.js.erb
$("#preferences").html("<%= j render(:partial => 'landing/preference', :locals => {:preferences => @preferences })%>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RLpreferences</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user.id %>
<%= link_to 'LOGOUT', destroy_user_session_path, :method => :delete %> <br>
<% end %>
<%= yield %>

</body>
</html>

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :enable %><br>
    <%= f.number_field :enable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h1>Editing preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

app/views/preferences/index.html.erb
<h1>Listing preferences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Order</th>
      <th>Enable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.name %></td>
        <td><%= preference.order %></td>
        <td><%= preference.enable %></td>
        <td><%= link_to 'Show', preference %></td>
        <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
        <td><%= link_to 'Destroy', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Set Preferences', new_preference_path %>

app/views/preferences/new.html.erb
<h1>New preference</h1>

<%= render 'form' %>

<%= link_to 'Back', preferences_path %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @preference.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @preference.order %>
</p>

<p>
  <strong>Enable:</strong>
  <%= @preference.enable %>
</p>

<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>